#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/f5--------------/ 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool RELAY1;
  bool RELAY2;
  bool RELAY3;
  bool RELAY4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#define PIN_RELAY1 2
#define PIN_RELAY2 4
#define PIN_RELAY3 15
#define PIN_RELAY4 12

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  pinMode(PIN_RELAY1, OUTPUT);
  pinMode(PIN_RELAY2, OUTPUT);
  pinMode(PIN_RELAY3, OUTPUT);
  pinMode(PIN_RELAY4, OUTPUT);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  digitalWrite(PIN_RELAY1, RELAY1);
  digitalWrite(PIN_RELAY2, RELAY2);
  digitalWrite(PIN_RELAY3, RELAY3);
  digitalWrite(PIN_RELAY4, RELAY4);
  
}

/*
  Since RELAY1 is READ_WRITE variable, onRELAY1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRELAY1Change()  {
  // Add your code here to act upon RELAY1 change
}
/*
  Since RELAY2 is READ_WRITE variable, onRELAY2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRELAY2Change()  {
  // Add your code here to act upon RELAY2 change
}
/*
  Since RELAY3 is READ_WRITE variable, onRELAY3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRELAY3Change()  {
  // Add your code here to act upon RELAY3 change
}
/*
  Since RELAY4 is READ_WRITE variable, onRELAY4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRELAY4Change()  {
  // Add your code here to act upon RELAY4 change
}
