// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "your-login-name";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRELAY1Change();
void onRELAY2Change();
void onRELAY3Change();
void onRELAY4Change();

bool RELAY1;
bool RELAY2;
bool RELAY3;
bool RELAY4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(RELAY1, READWRITE, 1 * SECONDS, onRELAY1Change);
  ArduinoCloud.addProperty(RELAY2, READWRITE, 1 * SECONDS, onRELAY2Change);
  ArduinoCloud.addProperty(RELAY3, READWRITE, 1 * SECONDS, onRELAY3Change);
  ArduinoCloud.addProperty(RELAY4, READWRITE, 1 * SECONDS, onRELAY4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
